project_id = "xkzhjldrojjlrkezorey"

[functions.stripe-webhook]
verify_jwt = false

[functions.send_event_to_sofinity]
verify_jwt = false

[functions.sofinity-integration-test]
verify_jwt = false

[functions.test-voucher-trigger]
verify_jwt = false

[functions.repair-missing-events]
verify_jwt = false