/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { useEffect,useMemo,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Planned={id:string;activity_type:string;scheduled_for:string;activity_status:string;body_snapshot:string|null;performed_by:string|null;metadata:Record<string,unknown>|null};
type Task={id:string;title:string;due_at:string;status:string;note:string|null;assigned_admin_id:string};
type Admin={id:string;full_name:string|null};
const localInput=(date=new Date())=>{const p=(n:number)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`;};
const czDate=(iso:string)=>new Intl.DateTimeFormat('cs-CZ',{timeZone:'Europe/Prague',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const typeLabel=(v:string)=>v==='meeting_logged'?'Schůzka':v==='call_logged'?'Telefonát':'Další krok';
const urgency=(iso:string)=>{const d=new Date(iso),now=new Date();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague'}).format(now)===new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague'}).format(d);return d<now?'Po termínu':today?'Dnes':'Nejbližší termín';};

export function LeadCrmPanel({leadId,status,emailApproved,onChanged}:{leadId:string;status:string;emailApproved:boolean;onChanged:()=>void}){
 const [kind,setKind]=useState('telefonat'),[result,setResult]=useState(''),[note,setNote]=useState(''),[next,setNext]=useState(''),[when,setWhen]=useState(localInput());
 const [planned,setPlanned]=useState<Planned[]>([]),[tasks,setTasks]=useState<Task[]>([]),[admins,setAdmins]=useState<Admin[]>([]),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[due,setDue]=useState(''),[assignee,setAssignee]=useState(''),[taskNote,setTaskNote]=useState('');
 const [fuSubject,setFuSubject]=useState(''),[fuBody,setFuBody]=useState(''); const names=useMemo(()=>new Map(admins.map(a=>[a.id,a.full_name||a.id.slice(0,8)])),[admins]);
 const load=async()=>{const [{data:a},{data:t},{data:r}]=await Promise.all([(supabase as any).from('sales_lead_activities').select('id,activity_type,scheduled_for,activity_status,body_snapshot,performed_by,metadata').eq('lead_id',leadId).in('activity_type',['call_logged','meeting_logged','note_added']).eq('activity_status','naplanovano').not('scheduled_for','is',null).order('scheduled_for'),(supabase as any).from('sales_lead_tasks').select('id,title,due_at,status,note,assigned_admin_id').eq('lead_id',leadId).order('due_at'),(supabase as any).from('user_roles').select('user_id').in('role',['admin','superadmin'])]);setPlanned(a??[]);setTasks(t??[]);const ids=[...new Set((r??[]).map((x:any)=>x.user_id))] as string[];const {data:p}=ids.length?await (supabase as any).from('profiles').select('id,full_name').in('id',ids):{data:[]};const nm=new Map((p??[]).map((x:any)=>[x.id,x.full_name]));const list=ids.map(id=>({id,full_name:nm.get(id)??null}));setAdmins(list);if(!assignee&&list[0])setAssignee(list[0].id);};
 useEffect(()=>{void load();},[leadId]);
 const clear=()=>{setResult('');setNote('');setNext('');setWhen(localInput());setEditing(null);};
 const saveActivity=async()=>{if(!result.trim()||!when)return toast.error('Doplňte účel a datum s časem.');setBusy(true);const date=new Date(when).toISOString();const {data}=editing?await (supabase as any).rpc('sales_lead_scheduled_activity_update',{p_activity_id:editing,p_scheduled_for:date,p_result:result,p_next_step:next||null,p_note:note||null}):await (supabase as any).rpc('sales_lead_log_activity',{p_lead_id:leadId,p_kind:kind,p_happened_at:date,p_result:result,p_next_step:next||null,p_note:note||null});setBusy(false);if(!data?.success)return toast.error('Aktivitu se nepodařilo uložit.');toast.success(editing?'Naplánovaná aktivita upravena.':data.scheduled?'Aktivita je vidět v sekci Naplánované aktivity.':'Aktivita uložena do historie.');clear();await load();onChanged();};
 const edit=(a:Planned)=>{setEditing(a.id);setKind(a.activity_type==='meeting_logged'?'schuzka':a.activity_type==='call_logged'?'telefonat':'poznamka');setWhen(localInput(new Date(a.scheduled_for)));setResult(String(a.metadata?.result??''));setNext(String(a.metadata?.next_step??''));setNote(a.body_snapshot??'');};
 const setActivityStatus=async(id:string,s:string)=>{const {data}=await (supabase as any).rpc('sales_lead_scheduled_activity_set_status',{p_activity_id:id,p_status:s});if(!data?.success)return toast.error('Stav se nepodařilo změnit.');toast.success(s==='dokonceno'?'Aktivita dokončena a přesunuta do historie.':'Aktivita zrušena a ponechána v historii.');await load();onChanged();};
 const addTask=async()=>{if(!title||!due||!assignee)return toast.error('Vyplňte úkol, termín a odpovědnou osobu.');setBusy(true);const {data}=await (supabase as any).rpc('sales_lead_task_create',{p_lead_id:leadId,p_title:title,p_due_at:new Date(due).toISOString(),p_assigned_admin_id:assignee,p_note:taskNote||null});setBusy(false);if(!data?.success)return toast.error('Úkol se nepodařilo vytvořit.');setTitle('');setDue('');setTaskNote('');await load();onChanged();};
 const finishTask=async(id:string,s:string)=>{const {data}=await (supabase as any).rpc('sales_lead_task_set_status',{p_task_id:id,p_status:s});if(!data?.success)return toast.error('Úkol se nepodařilo změnit.');await load();onChanged();};
 const draftFollowUp=async()=>{setBusy(true);const {data,error}=await supabase.functions.invoke('sales-lead-draft-email',{body:{lead_id:leadId,mode:'follow_up'}});setBusy(false);if(error||!data?.success)return toast.error('Follow-up nyní nelze připravit.');setFuSubject(data.subject);setFuBody(data.body);};
 const sendFollowUp=async()=>{if(!confirm('Opravdu ručně odeslat tento follow-up?'))return;setBusy(true);const {data,error}=await supabase.functions.invoke('send-sales-lead-follow-up',{body:{lead_id:leadId,subject:fuSubject,body:fuBody}});setBusy(false);if(error||!data?.success)return toast.error(`Follow-up nebyl odeslán (${data?.error??'chyba'}).`);toast.success('Follow-up odeslán.');setFuSubject('');setFuBody('');onChanged();};
 return <div className="space-y-5">
  <section className="rounded-lg border-2 border-primary/30 bg-primary/5 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Naplánované aktivity</h3><Badge>{planned.length}</Badge></div>{planned.length===0?<p className="text-sm text-muted-foreground">Žádná naplánovaná schůzka, telefonát ani další krok.</p>:<div className="space-y-3">{planned.map((a,i)=><article key={a.id} className={`rounded-lg border bg-background p-3 ${new Date(a.scheduled_for)<new Date()?'border-destructive':''}`}><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{typeLabel(a.activity_type)}</Badge><Badge variant={new Date(a.scheduled_for)<new Date()?'destructive':'secondary'}>{i===0?urgency(a.scheduled_for):new Date(a.scheduled_for)<new Date()?'Po termínu':''}</Badge><strong className="text-base">{czDate(a.scheduled_for)}</strong></div><div className="mt-2 text-sm"><div><strong>Účel/výsledek:</strong> {String(a.metadata?.result??'—')}</div><div><strong>Poznámka:</strong> {a.body_snapshot||'—'}</div><div><strong>Následující krok:</strong> {String(a.metadata?.next_step??'—')}</div><div><strong>Autor:</strong> {a.performed_by?names.get(a.performed_by)||a.performed_by.slice(0,8):'Systém'}</div></div><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={()=>edit(a)}>Upravit</Button><Button size="sm" onClick={()=>setActivityStatus(a.id,'dokonceno')}>Dokončit</Button><Button size="sm" variant="ghost" onClick={()=>setActivityStatus(a.id,'zruseno')}>Zrušit</Button></div></article>)}</div>}</section>
  <section className="rounded-lg border p-4"><h3 className="mb-2 font-semibold">{editing?'Upravit naplánovanou aktivitu':'Zapsat nebo naplánovat aktivitu'}</h3><div className="grid gap-2 sm:grid-cols-2"><Select value={kind} onValueChange={setKind} disabled={!!editing}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="telefonat">Telefonát</SelectItem><SelectItem value="schuzka">Schůzka</SelectItem><SelectItem value="poznamka">Další krok / poznámka</SelectItem></SelectContent></Select><Input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><Input placeholder="Účel nebo výsledek" value={result} onChange={e=>setResult(e.target.value)}/><Input placeholder="Následující krok (volitelný)" value={next} onChange={e=>setNext(e.target.value)}/></div><Textarea className="mt-2" placeholder="Poznámka (volitelná)" value={note} onChange={e=>setNote(e.target.value)}/><div className="mt-2 flex gap-2"><Button size="sm" disabled={busy} onClick={saveActivity}>{editing?'Uložit změny':'Uložit aktivitu'}</Button>{editing&&<Button size="sm" variant="ghost" onClick={clear}>Zrušit úpravu</Button>}</div><p className="mt-2 text-xs text-muted-foreground">Čas zadáváte v českém čase. Budoucí termín se zobrazí nahoře v Naplánovaných aktivitách.</p></section>
  <section className="rounded-lg border p-4"><h3 className="mb-2 font-semibold">Úkoly a připomenutí</h3><div className="space-y-2">{tasks.map(t=><div key={t.id} className={`flex flex-wrap items-center gap-2 rounded border p-2 ${t.status==='ceka'&&new Date(t.due_at)<new Date()?'border-destructive bg-destructive/5':''}`}><span className="font-medium">{t.title}</span><Badge variant="outline">{t.status}</Badge><span className="text-xs">{czDate(t.due_at)}</span>{t.status==='ceka'&&<><Button size="sm" variant="outline" onClick={()=>finishTask(t.id,'dokonceno')}>Dokončit</Button><Button size="sm" variant="ghost" onClick={()=>finishTask(t.id,'zruseno')}>Zrušit</Button></>}</div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input placeholder="Název úkolu" value={title} onChange={e=>setTitle(e.target.value)}/><Input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/><Select value={assignee} onValueChange={setAssignee}><SelectTrigger><SelectValue placeholder="Odpovědný administrátor"/></SelectTrigger><SelectContent>{admins.map(a=><SelectItem key={a.id} value={a.id}>{a.full_name||a.id.slice(0,8)}</SelectItem>)}</SelectContent></Select><Input placeholder="Poznámka" value={taskNote} onChange={e=>setTaskNote(e.target.value)}/></div><Button className="mt-2" size="sm" disabled={busy} onClick={addTask}>Vytvořit úkol</Button></section>
  <section className="rounded-lg border p-4"><h3 className="mb-1 font-semibold">Follow-up bez odpovědi</h3><p className="mb-2 text-xs text-muted-foreground">Odeslání je vždy ruční.</p><Button size="sm" variant="outline" disabled={!['osloveno','follow_up'].includes(status)||!emailApproved||busy} onClick={draftFollowUp}>Připravit AI návrh follow-upu</Button>{fuSubject&&<div className="mt-2 space-y-2"><Label>Předmět</Label><Input value={fuSubject} onChange={e=>setFuSubject(e.target.value)}/><Label>Text</Label><Textarea rows={7} value={fuBody} onChange={e=>setFuBody(e.target.value)}/><Button disabled={busy||!fuBody.trim()} onClick={sendFollowUp}>Ručně odeslat follow-up</Button></div>}</section>
 </div>;
}
