/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Task={id:string;title:string;due_at:string;status:string;note:string|null;assigned_admin_id:string};
type Admin={id:string;full_name:string|null};
export function LeadCrmPanel({leadId,status,emailApproved,onChanged}:{leadId:string;status:string;emailApproved:boolean;onChanged:()=>void}){
 const [kind,setKind]=useState('telefonat'),[result,setResult]=useState(''),[note,setNote]=useState(''),[next,setNext]=useState('');
 const [when,setWhen]=useState(new Date().toISOString().slice(0,16)); const [tasks,setTasks]=useState<Task[]>([]),[admins,setAdmins]=useState<Admin[]>([]);
 const [title,setTitle]=useState(''),[due,setDue]=useState(''),[assignee,setAssignee]=useState(''),[taskNote,setTaskNote]=useState('');
 const [fuSubject,setFuSubject]=useState(''),[fuBody,setFuBody]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const [{data:t},{data:r}]=await Promise.all([(supabase as any).from('sales_lead_tasks').select('id,title,due_at,status,note,assigned_admin_id').eq('lead_id',leadId).order('due_at'),(supabase as any).from('user_roles').select('user_id').in('role',['admin','superadmin'])]);setTasks(t??[]);const ids=[...new Set((r??[]).map((x:any)=>x.user_id))] as string[];const {data:p}=ids.length?await (supabase as any).from('profiles').select('id,full_name').in('id',ids):{data:[]};const names=new Map((p??[]).map((x:any)=>[x.id,x.full_name]));const a=ids.map(id=>({id,full_name:names.get(id)??null}));setAdmins(a);if(!assignee&&a[0])setAssignee(a[0].id);};
 useEffect(()=>{void load();},[leadId]);
 const log=async()=>{if(!result.trim())return toast.error('Doplňte výsledek.');setBusy(true);const {data}=await (supabase as any).rpc('sales_lead_log_activity',{p_lead_id:leadId,p_kind:kind,p_happened_at:new Date(when).toISOString(),p_result:result,p_next_step:next||null,p_note:note||null});setBusy(false);if(!data?.success)return toast.error('Záznam se nepodařilo uložit.');setResult('');setNote('');setNext('');toast.success('Záznam uložen.');onChanged();};
 const addTask=async()=>{if(!title||!due||!assignee)return toast.error('Vyplňte úkol, termín a odpovědnou osobu.');setBusy(true);const {data}=await (supabase as any).rpc('sales_lead_task_create',{p_lead_id:leadId,p_title:title,p_due_at:new Date(due).toISOString(),p_assigned_admin_id:assignee,p_note:taskNote||null});setBusy(false);if(!data?.success)return toast.error('Úkol se nepodařilo vytvořit.');setTitle('');setDue('');setTaskNote('');await load();onChanged();};
 const finish=async(id:string,s:string)=>{const {data}=await (supabase as any).rpc('sales_lead_task_set_status',{p_task_id:id,p_status:s});if(!data?.success)return toast.error('Úkol se nepodařilo změnit.');await load();onChanged();};
 const draftFollowUp=async()=>{setBusy(true);const {data,error}=await supabase.functions.invoke('sales-lead-draft-email',{body:{lead_id:leadId,mode:'follow_up'}});setBusy(false);if(error||!data?.success)return toast.error('Follow-up nyní nelze připravit.');setFuSubject(data.subject);setFuBody(data.body);};
 const sendFollowUp=async()=>{if(!confirm('Opravdu ručně odeslat tento follow-up?'))return;setBusy(true);const {data,error}=await supabase.functions.invoke('send-sales-lead-follow-up',{body:{lead_id:leadId,subject:fuSubject,body:fuBody}});setBusy(false);if(error||!data?.success)return toast.error(`Follow-up nebyl odeslán (${data?.error??'chyba'}).`);toast.success('Follow-up odeslán.');setFuSubject('');setFuBody('');onChanged();};
 const followAllowed=['osloveno','follow_up'].includes(status)&&emailApproved;
 return <div className="space-y-5 rounded-lg border p-4">
  <div><div className="mb-2 text-sm font-semibold">Telefonát, schůzka nebo poznámka</div><div className="grid gap-2 sm:grid-cols-2"><Select value={kind} onValueChange={setKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="telefonat">Telefonát</SelectItem><SelectItem value="schuzka">Schůzka</SelectItem><SelectItem value="poznamka">Poznámka</SelectItem></SelectContent></Select><Input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><Input placeholder="Výsledek kontaktu" value={result} onChange={e=>setResult(e.target.value)}/><Input placeholder="Následující krok (volitelný)" value={next} onChange={e=>setNext(e.target.value)}/></div><Textarea className="mt-2" placeholder="Podrobnosti (volitelné)" value={note} onChange={e=>setNote(e.target.value)}/><Button className="mt-2" size="sm" disabled={busy} onClick={log}>Uložit záznam</Button></div>
  <div><div className="mb-2 text-sm font-semibold">Úkoly a připomenutí</div><div className="space-y-2">{tasks.map(t=><div key={t.id} className={`flex flex-wrap items-center gap-2 rounded border p-2 ${t.status==='ceka'&&new Date(t.due_at)<new Date()?'border-destructive bg-destructive/5':''}`}><span className="font-medium">{t.title}</span><Badge variant="outline">{t.status}</Badge><span className="text-xs text-muted-foreground">{new Date(t.due_at).toLocaleString('cs-CZ')}</span>{t.status==='ceka'&&<><Button size="sm" variant="outline" onClick={()=>finish(t.id,'dokonceno')}>Dokončit</Button><Button size="sm" variant="ghost" onClick={()=>finish(t.id,'zruseno')}>Zrušit</Button></>}</div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input placeholder="Název úkolu" value={title} onChange={e=>setTitle(e.target.value)}/><Input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/><Select value={assignee} onValueChange={setAssignee}><SelectTrigger><SelectValue placeholder="Odpovědný administrátor"/></SelectTrigger><SelectContent>{admins.map(a=><SelectItem key={a.id} value={a.id}>{a.full_name||a.id.slice(0,8)}</SelectItem>)}</SelectContent></Select><Input placeholder="Poznámka" value={taskNote} onChange={e=>setTaskNote(e.target.value)}/></div><Button className="mt-2" size="sm" disabled={busy} onClick={addTask}>Vytvořit úkol</Button></div>
  <div><div className="mb-1 text-sm font-semibold">Follow-up bez odpovědi</div><p className="mb-2 text-xs text-muted-foreground">Doporučený termín: 5 pracovních dnů od posledního e-mailu. Odeslání je vždy ruční.</p><Button size="sm" variant="outline" disabled={!followAllowed||busy} onClick={draftFollowUp}>Připravit AI návrh follow-upu</Button>{!followAllowed&&<p className="mt-1 text-xs text-destructive">Follow-up je dostupný jen u osloveného leadu se schváleným e-mailem.</p>}{fuSubject&&<div className="mt-2 space-y-2"><Label>Předmět</Label><Input value={fuSubject} onChange={e=>setFuSubject(e.target.value)}/><Label>Text</Label><Textarea rows={7} value={fuBody} onChange={e=>setFuBody(e.target.value)}/><Button disabled={busy||!fuBody.trim()} onClick={sendFollowUp}>Ručně odeslat follow-up</Button></div>}</div>
 </div>;
}
