import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const GRAPH_API_VERSION = "v26.0";
const PAGE_ID = "842044862333348";
const INSTAGRAM_ACCOUNT_ID = "17841438461126638";
const BROKER_KEY_HEADER = "x-paperclip-broker-key";
const MAX_MEDIA_LIMIT = 25;

type Operation = "page_profile" | "page_insights" | "instagram_profile" | "instagram_media" | "instagram_insights";
type RuntimeConfig = { page_id: string; instagram_account_id: string; broker_key_sha256: string };

function response(body: unknown, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } }); }
function fail(error: string, status: number): Response { return response({ error }, status); }
async function hash(value: string): Promise<string> { const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(d), (b) => b.toString(16).padStart(2, "0")).join(""); }
function adminKey(): string | null { try { const keys = JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") || "{}") as Record<string, unknown>; for (const name of ["backend_api", "default"]) { const value = keys[name]; if (typeof value === "string" && value.length > 0) return value; } } catch {} return null; }
function headers(): HeadersInit { const key = adminKey(); if (!key) throw new Error("broker_runtime_unavailable"); return { "Content-Type": "application/json", apikey: key }; }
async function rpc(name: string, args: Record<string, unknown> = {}): Promise<unknown> { const base = Deno.env.get("SUPABASE_URL"); if (!base) throw new Error("broker_runtime_unavailable"); const r = await fetch(`${base}/rest/v1/rpc/${name}`, { method: "POST", headers: headers(), body: JSON.stringify(args) }); if (!r.ok) throw new Error(name === "meta_broker_get_page_access_token" ? "broker_not_connected" : "broker_not_configured"); return await r.json(); }
async function authorized(req: Request): Promise<boolean> { const key = req.headers.get(BROKER_KEY_HEADER); if (!key || key.length < 32 || key.length > 512) return false; const rows = await rpc("meta_broker_get_runtime_config") as RuntimeConfig[]; if (!Array.isArray(rows) || rows.length !== 1) return false; const c = rows[0]; return c.page_id === PAGE_ID && c.instagram_account_id === INSTAGRAM_ACCOUNT_ID && /^[0-9a-f]{64}$/.test(c.broker_key_sha256) && (await hash(key)) === c.broker_key_sha256; }
function operation(input: unknown): Operation | null { const value = input && typeof input === "object" && !Array.isArray(input) ? (input as Record<string, unknown>).operation : null; return value === "page_profile" || value === "page_insights" || value === "instagram_profile" || value === "instagram_media" || value === "instagram_insights" ? value : null; }
function limit(input: unknown): number { const n = input && typeof input === "object" && !Array.isArray(input) ? Number((input as Record<string, unknown>).limit) : NaN; return Number.isInteger(n) && n >= 1 && n <= MAX_MEDIA_LIMIT ? n : 10; }
function metrics(op: Operation, input: unknown): string { const defaults = op === "page_insights" ? ["page_impressions", "page_reach"] : ["views", "reach", "total_interactions"]; const value = input && typeof input === "object" && !Array.isArray(input) ? (input as Record<string, unknown>).metrics : null; if (!Array.isArray(value) || value.length === 0 || value.some((x) => typeof x !== "string" || !defaults.includes(x))) return defaults.join(","); return value.join(","); }
async function graph(path: string, params: Record<string, string>): Promise<unknown> { const token = await rpc("meta_broker_get_page_access_token"); if (typeof token !== "string" || token.length < 16) throw new Error("broker_not_connected"); const url = new URL(`https://graph.facebook.com/${GRAPH_API_VERSION}/${path}`); for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v); url.searchParams.set("access_token", token); const r = await fetch(url); if (!r.ok) throw new Error("meta_read_failed"); const payload = await r.json(); if (!payload || typeof payload !== "object") throw new Error("meta_read_failed"); const record = payload as Record<string, unknown>; return Array.isArray(record.data) ? { data: record.data } : record; }

Deno.serve(async (req) => { const url = new URL(req.url); const route = url.pathname.replace(/^.*\/meta-read-broker/, "") || "/"; if (route === "/health" && req.method === "GET") return response({ service: "meta-read-broker", environment: "production", status: "ready" }); if (route !== "/read") return fail("not_found", 404); if (req.method !== "POST") return fail("method_not_allowed", 405); try { if (!(await authorized(req))) return fail("broker_access_denied", 403); const input: unknown = await req.json().catch(() => null); const op = operation(input); if (!op) return fail("operation_not_allowed", 403); const n = limit(input); if (op === "page_profile") return response(await graph(PAGE_ID, { fields: "id,name,link,fan_count,followers_count,picture{url}" })); if (op === "page_insights") return response(await graph(`${PAGE_ID}/insights`, { metric: metrics(op, input), period: "day" })); if (op === "instagram_profile") return response(await graph(INSTAGRAM_ACCOUNT_ID, { fields: "id,username,name,biography,followers_count,follows_count,media_count,profile_picture_url,website" })); if (op === "instagram_media") return response(await graph(`${INSTAGRAM_ACCOUNT_ID}/media`, { fields: "id,caption,media_type,media_url,permalink,thumbnail_url,timestamp,like_count,comments_count", limit: String(n) })); return response(await graph(`${INSTAGRAM_ACCOUNT_ID}/insights`, { metric: metrics(op, input), period: "day" })); } catch (e) { const code = e instanceof Error && ["broker_not_configured", "broker_not_connected", "broker_runtime_unavailable"].includes(e.message) ? e.message : "meta_read_failed"; return fail(code, code === "broker_not_configured" || code === "broker_not_connected" ? 503 : 502); } });
