import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const VERSION = "v26.0";
const PAGE_ID = "842044862333348";
const INSTAGRAM_ID = "17841438461126638";
const TTL = 10 * 60 * 1000;
const encoder = new TextEncoder();

type Config = { appId: string; appSecret: string; configId: string; redirectUri: string; stateSecret: string };
type Page = { id?: string; access_token?: string; instagram_business_account?: { id?: string } };
function json(body: unknown, status = 200, headers: HeadersInit = {}): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff", ...headers } }); }
function config(): Config { const c = { appId: Deno.env.get("META_APP_ID") || "", appSecret: Deno.env.get("META_APP_SECRET") || "", configId: Deno.env.get("META_OAUTH_CONFIG_ID") || "", redirectUri: Deno.env.get("META_OAUTH_REDIRECT_URI") || "", stateSecret: Deno.env.get("META_OAUTH_STATE_SECRET") || "" }; if (Object.values(c).some((v) => !v)) throw new Error("oauth_configuration_unavailable"); return c; }
function b64(v: Uint8Array | string): string { const bytes = typeof v === "string" ? encoder.encode(v) : v; let s = ""; for (const b of bytes) s += String.fromCharCode(b); return btoa(s).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function unb64(v: string): Uint8Array { const n = v.replaceAll("-", "+").replaceAll("_", "/"); const s = atob(n + "=".repeat((4 - n.length % 4) % 4)); return Uint8Array.from(s, (c) => c.charCodeAt(0)); }
async function sign(v: string, secret: string): Promise<string> { const k = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return b64(new Uint8Array(await crypto.subtle.sign("HMAC", k, encoder.encode(v)))); }
function equal(a: string, b: string): boolean { if (a.length !== b.length) return false; let d = 0; for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i); return d === 0; }
async function createState(secret: string): Promise<string> { const nonce = new Uint8Array(24); crypto.getRandomValues(nonce); const payload = b64(JSON.stringify({ iat: Date.now(), nonce: b64(nonce) })); return `${payload}.${await sign(payload, secret)}`; }
async function verifyState(value: string, secret: string): Promise<void> { const [payload, signature, extra] = value.split("."); if (!payload || !signature || extra || !equal(await sign(payload, secret), signature)) throw new Error("oauth_callback_failed"); const parsed = JSON.parse(new TextDecoder().decode(unb64(payload))) as { iat?: number; nonce?: string }; if (!Number.isInteger(parsed.iat) || !parsed.nonce || Date.now() - parsed.iat! > TTL || parsed.iat! > Date.now() + 30000) throw new Error("oauth_state_expired"); }
function cookie(req: Request): string | null { const item = req.headers.get("cookie")?.split(";").map((x) => x.trim()).find((x) => x.startsWith("meta_oauth_state=")); return item ? decodeURIComponent(item.slice(17)) : null; }
function setCookie(v: string): string { return `meta_oauth_state=${encodeURIComponent(v)}; Path=/functions/v1/meta-oauth-callback; HttpOnly; Secure; SameSite=Lax; Max-Age=600`; }
const clearCookie = "meta_oauth_state=; Path=/functions/v1/meta-oauth-callback; HttpOnly; Secure; SameSite=Lax; Max-Age=0";
async function exchange(code: string, c: Config): Promise<string> { const u = new URL(`https://graph.facebook.com/${VERSION}/oauth/access_token`); u.searchParams.set("client_id", c.appId); u.searchParams.set("client_secret", c.appSecret); u.searchParams.set("redirect_uri", c.redirectUri); u.searchParams.set("code", code); const r = await fetch(u); const p = await r.json().catch(() => ({})) as { access_token?: string }; if (!r.ok || !p.access_token) throw new Error("oauth_token_exchange_failed"); return p.access_token; }
async function page(token: string): Promise<Page> { const u = new URL(`https://graph.facebook.com/${VERSION}/${PAGE_ID}`); u.searchParams.set("fields", "id,access_token,instagram_business_account"); u.searchParams.set("access_token", token); const r = await fetch(u); const p = await r.json().catch(() => ({})) as Page; if (!r.ok || p.id !== PAGE_ID || !p.access_token || p.instagram_business_account?.id !== INSTAGRAM_ID) throw new Error("authorized_asset_not_found"); return p; }
async function verifyRead(token: string): Promise<{ media: boolean; insights: boolean }> { const media = new URL(`https://graph.facebook.com/${VERSION}/${INSTAGRAM_ID}/media`); media.searchParams.set("fields", "id"); media.searchParams.set("limit", "1"); media.searchParams.set("access_token", token); const insights = new URL(`https://graph.facebook.com/${VERSION}/${INSTAGRAM_ID}/insights`); insights.searchParams.set("metric", "views"); insights.searchParams.set("period", "day"); insights.searchParams.set("metric_type", "total_value"); insights.searchParams.set("access_token", token); const [a, b] = await Promise.all([fetch(media), fetch(insights)]); return { media: a.ok, insights: b.ok }; }
async function store(token: string): Promise<void> { const base = Deno.env.get("SUPABASE_URL"); const key = adminKey(); if (!base || !key) throw new Error("oauth_token_storage_failed"); const r = await fetch(`${base}/rest/v1/rpc/meta_broker_store_page_access_token`, { method: "POST", headers: { "Content-Type": "application/json", apikey: key }, body: JSON.stringify({ p_token: token }) }); if (!r.ok) throw new Error("oauth_token_storage_failed"); }
function adminKey(): string | null { try { const keys = JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") || "{}") as Record<string, unknown>; for (const name of ["backend_api", "default"]) { const value = keys[name]; if (typeof value === "string" && value.length > 0) return value; } } catch {} return null; }
Deno.serve(async (req) => { if (req.method !== "GET") return json({ error: "method_not_allowed" }, 405, { Allow: "GET" }); const url = new URL(req.url); const route = url.pathname.replace(/^.*\/meta-oauth-callback/, "") || "/"; if (route === "/" || route === "/health") return json({ service: "meta-oauth-callback", environment: "production", status: "ready" }); if (route === "/start") { try { const c = config(); const state = await createState(c.stateSecret); const login = new URL(`https://www.facebook.com/${VERSION}/dialog/oauth`); login.searchParams.set("client_id", c.appId); login.searchParams.set("redirect_uri", c.redirectUri); login.searchParams.set("response_type", "code"); login.searchParams.set("config_id", c.configId); login.searchParams.set("state", state); return new Response(null, { status: 302, headers: { Location: login.toString(), "Set-Cookie": setCookie(state), "Cache-Control": "no-store" } }); } catch { return json({ error: "oauth_configuration_unavailable" }, 503); } } if (route !== "/callback") return json({ error: "not_found" }, 404); const code = url.searchParams.get("code"); const state = url.searchParams.get("state"); if (url.searchParams.get("error")) return json({ error: "oauth_denied" }, 400, { "Set-Cookie": clearCookie }); if (!code || !state) return json({ error: "missing_code_or_state" }, 400, { "Set-Cookie": clearCookie }); try { const c = config(); if (cookie(req) !== state) throw new Error("oauth_state_cookie_mismatch"); await verifyState(state, c.stateSecret); const userToken = await exchange(code, c); const selectedPage = await page(userToken); const verification = await verifyRead(selectedPage.access_token!); if (!verification.media || !verification.insights) throw new Error("read_scope_unavailable"); await store(selectedPage.access_token!); return json({ connected: true, pageId: PAGE_ID, instagramAccountId: INSTAGRAM_ID, readAccess: verification }, 200, { "Set-Cookie": clearCookie }); } catch (e) { const m = e instanceof Error && ["oauth_state_expired", "oauth_state_cookie_mismatch", "authorized_asset_not_found", "read_scope_unavailable", "oauth_token_exchange_failed", "oauth_token_storage_failed", "oauth_configuration_unavailable"].includes(e.message) ? e.message : "oauth_callback_failed"; return json({ error: m }, m === "oauth_state_expired" ? 400 : 502, { "Set-Cookie": clearCookie }); } });
